"use client";

import React from "react";
import { marked } from "marked";
import { MathJaxContext } from "better-react-mathjax";
import { mjxConfig } from "./RichBlock";

export default function ReadingRenderer({ content }) {
  // Parse markdown to HTML
  // gfm: true enables GitHub Flavored Markdown (tables, etc.)
  const htmlContent = marked.parse(content || "", { gfm: true });

  return (
    <MathJaxContext config={mjxConfig}>
      <div
        className="prose prose-sm max-w-none text-[var(--foreground)]"
        // dangerouslySetInnerHTML is used to render the HTML generated by marked
        dangerouslySetInnerHTML={{ __html: htmlContent }}
      />
      {/* Optional styles for details/summary if not covered by global CSS */}
      <style jsx global>{`
        .prose details > summary {
          cursor: pointer;
          font-weight: 500;
          color: var(--foreground);
        }
        .prose details[open] > summary {
          margin-bottom: 0.5rem;
        }
        .prose img {
          max-width: 100%;
          height: auto;
          border-radius: 0.5rem;
        }
      `}</style>
    </MathJaxContext>
  );
}
